# Homework 3

## Problem 1: (Methods)

In [10]:
atmosphere = ["Trophosphere", "Mesophere", "Mantle", "Thermosphere"] #defining list

### Problem 1.1

In [11]:
atmosphere.remove("Mantle") #removing "Mantle" from list
atmosphere

['Trophosphere', 'Mesophere', 'Thermosphere']

### Problem 1.2

In [12]:
atmosphere.append("Exposphere") #adding "Exposphere" from list
atmosphere

['Trophosphere', 'Mesophere', 'Thermosphere', 'Exposphere']

### Problem 1.3

In [13]:
atmosphere.index("Thermosphere") #finding index of "Thermosphere"

2

### Problem 1.4

In [14]:
atmosphere.insert(1,"Stratosphere") #inserting "Stratosphere" in between "Troposphere" and "Mesophere"
atmosphere

['Trophosphere', 'Stratosphere', 'Mesophere', 'Thermosphere', 'Exposphere']

### Problem 1.5

In [15]:
atmosphere.reverse() #reversing list
atmosphere

['Exposphere', 'Thermosphere', 'Mesophere', 'Stratosphere', 'Trophosphere']

### Problem  1.6

In [16]:
print("{} is a list of the layers of the atmosphere, from highest to lowest.".format(atmosphere)) #printing list in sentence

['Exposphere', 'Thermosphere', 'Mesophere', 'Stratosphere', 'Trophosphere'] is a list of the layers of the atmosphere, from highest to lowest.


## Problem 2: (Tuples)

### Problem 2.1

In [1]:
magnitude = (2.5, 2.5, 2.61, 3.24, 2.78, 2.7, 2.64, 3.5, 2.5, 3.42, 2.6, 3.46) #defining tuple with magnitudes

### Problem 2.2

In [2]:
magnitude[7] = 4.5 #trying to replace 3.5 with 4.5, getting an error

TypeError: 'tuple' object does not support item assignment

### Problem 2.3

In [3]:
print(min(magnitude)) #minimum of magnitudes
print(max(magnitude)) #maximum of magnitudes

2.5
3.5


### Problem 2.4

In [4]:
magnitude.count(2.5) #how many times 2.5 appears

3

### Problem 2.5

In [5]:
magnitude.index(2.6) #what index 2.6 is

10

### Problem 2.6

In [9]:
sorted(magnitude) #sorted magnitude, final resorted dataset is a list, but magnitude is still a tuple

[2.5, 2.5, 2.5, 2.6, 2.61, 2.64, 2.7, 2.78, 3.24, 3.42, 3.46, 3.5]

### Problem 2.7

<font color = 'red'> Why are tuples useful?</font> Tuples are useful because you cannot change the values inside of them. So, when reading the code, you can expect it to stay constant. In case if you make a mistake of accidentally changing something, the tuple will prevent anything like that from occurring. Also, they run faster than lists. Source: [here](https://eng.libretexts.org/Bookshelves/Computer_Science/Book%3A_Making_Games_with_Python_and_Pygame_(Sweigart)/04%3A_Memory_Puzzle/4.12%3A_Tuples_vs._Lists%2C_Immutable_vs._Mutable)

### Problem 2.8

In [15]:
months = {'01':'January','02':'February','03':'March','04':'April','05':'May','06':'June',
 '07':'July','08':'August','09':'September','10':'October','11':'November','12':'December'} #defining dictionary "months"

october = months['10'] #assigning October to variable

### Problem 2.9

In [16]:
print("On {} 18th, 2020, the strongest Earthquake recorded in United States and Canada was {}.".format(october,max(magnitude)))

On October 18th, 2020, the strongest Earthquake recorded in United States and Canada was 3.5.


## Problem 3 (Basic Arrays and Calculator Questions)

In [1]:
import numpy as np

### Problem 3.1

In [3]:
a = np.arange(-4,4.5,0.5) #create an array ranging from -4 to 4.5, with 0.5 intervals in between number
a

array([-4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,
        1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

### Problem 3.2

In [19]:
b = 7*a
b

array([-28. , -24.5, -21. , -17.5, -14. , -10.5,  -7. ,  -3.5,   0. ,
         3.5,   7. ,  10.5,  14. ,  17.5,  21. ,  24.5,  28. ])

### Problem 3.3

In [20]:
c = a + 2.3
c

array([-1.7, -1.2, -0.7, -0.2,  0.3,  0.8,  1.3,  1.8,  2.3,  2.8,  3.3,
        3.8,  4.3,  4.8,  5.3,  5.8,  6.3])

### Problem 3.4

In [21]:
d = a**2
d

array([16.  , 12.25,  9.  ,  6.25,  4.  ,  2.25,  1.  ,  0.25,  0.  ,
        0.25,  1.  ,  2.25,  4.  ,  6.25,  9.  , 12.25, 16.  ])

### Problem 3.5

In [22]:
e = np.sqrt(d)
e

# It's not exactly a as all the once negative numbers that were squared became positive when taken the 
# square root. Thus, that's the difference that wasn't exactly expected.

array([4. , 3.5, 3. , 2.5, 2. , 1.5, 1. , 0.5, 0. , 0.5, 1. , 1.5, 2. ,
       2.5, 3. , 3.5, 4. ])

### Problem 3.6

In [23]:
f = np.sin(a)
f

array([ 0.7568025 ,  0.35078323, -0.14112001, -0.59847214, -0.90929743,
       -0.99749499, -0.84147098, -0.47942554,  0.        ,  0.47942554,
        0.84147098,  0.99749499,  0.90929743,  0.59847214,  0.14112001,
       -0.35078323, -0.7568025 ])

## Problem 4 (Array Manipulation Part 1)

### Problem 4.1

In [24]:
x = np.arange(0,12,1) #create an array from 0 to 11
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Problem 4.2

In [25]:
np.shape(x) #shape is 12 x 1

(12,)

### Problem 4.3

In [26]:
y = np.reshape(x, (3,4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Problem 4.4

In [27]:
y[2,2] #index row 2, then index column 2

10

### Problem 4.5

In [28]:
y[:,2] #everything in index column 2

array([ 2,  6, 10])

### Problem 4.6

In [29]:
y[0,:] #everything in index row 0

array([0, 1, 2, 3])

## Problem 5 (Array Manipulation)

### Problem 5.1

In [30]:
A = 5 * np.ones((10,10)) #creating 10 x 10 full of ones and then multiplying all contents by 5
A

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

### Problem 5.2

In [31]:
B = np.ones((8,8)) #create an 8x8 full of ones
B[1:7,1:7] = 0 #set those indexes (7x7) to zero
B

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### Problem 5.3

In [32]:
C = np.zeros((8,8)) #creating 8x8 zero grid

#inserting ones
C[::2,1::2] = 1 #even rows
C[1::2,::2] = 1 #odd rows

C

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### Problem 5.4

In [33]:
#outputting size, mean, and standard deviation from above matrices

#5.1
print("{} has the size {}, mean {}, and standard deviation {}.".format('5.1 matrix', A.size, np.mean(A), np.std(A)))

#5.2
print("{} has the size {}, mean {}, and standard deviation {}.".format('5.2 matrix', B.size, np.mean(B), np.std(B)))

#5.3
print("{} has the size {}, mean {}, and standard deviation {}.".format('5.3 matrix', C.size, np.mean(C), np.std(C)))

5.1 matrix has the size 100, mean 5.0, and standard deviation 0.0.
5.2 matrix has the size 64, mean 0.4375, and standard deviation 0.49607837082461076.
5.3 matrix has the size 64, mean 0.5, and standard deviation 0.5.


## Problem 6 (Geophysical Pressure Estimates)

### Problem 6.1

In [19]:
density = np.array([1.0,1000,2800,4000,5500]) #density,kg/m^3 (atm, ocean, litho, cmb, and center of planet)

### Problem 6.2

In [35]:
depth = np.array([10,4,35,2886,6371]) #depth, km

### Problem 6.3

In [36]:
p_0 = 0 #pressure at the top surface of the layer, Pa
g = 9.8 #gravity, m/s^2

p = p_0 + density*depth*g #pressure at bottom of a layer, Pa
p

array([9.800000e+01, 3.920000e+04, 9.604000e+05, 1.131312e+08,
       3.433969e+08])

### Problem 6.4

In [37]:
p_bar = p/(10**5) #converting to bars from Pa, 1 bar = 10^5 Pa
p_bar

array([9.800000e-04, 3.920000e-01, 9.604000e+00, 1.131312e+03,
       3.433969e+03])

## Problem 7 (Hot Spots)

### Problem 7.1

In [20]:
distance = np.array([290,519,2432,4860]) #distance from hot spot, km (Moloka'i, Kaua'i, Midway, Suiko)

### Problem 7.2

In [21]:
age = np.array([1.8,5.0,28.0,65.0]) #age of island, in millions of years old (Ma)

### Problem 7.3

In [22]:
velocity = distance / age #velocity of island
velocity #km/Ma

array([161.11111111, 103.8       ,  86.85714286,  74.76923077])

### Problem 7.4

In [23]:
velocity_cmyear = velocity * (10**5) * (1 / 10**6) #converting km/Ma to cm/year, 1 km = 10^5 cm, 
                                                #1 Ma = 10^6 years
velocity_cmyear #cm/year

array([16.11111111, 10.38      ,  8.68571429,  7.47692308])

### Problem 7.5

In [24]:
print(np.mean(velocity_cmyear)) #average of velocity array, cm/year

10.663437118437118


## Problem 8 (Working with Mid-Ocean Ridge (MOR) Data)

### Problem 8.1

In [43]:
seafloor_crust = np.array([[160,115,115,112,112,10.3,37,163,80],[5460,5634,5734,5749,5750,3905,4558,5876,5937]])
#first index is age in Ma, second index is depth in m
seafloor_crust

array([[ 160. ,  115. ,  115. ,  112. ,  112. ,   10.3,   37. ,  163. ,
          80. ],
       [5460. , 5634. , 5734. , 5749. , 5750. , 3905. , 4558. , 5876. ,
        5937. ]])

### Problem 8.2

In [44]:
seafloor_crust.shape #shape of array, 2 rows and 9 columns

(2, 9)

### Problem 8.3

In [45]:
seafloor_crust[0,:] #everything in first row is age

array([160. , 115. , 115. , 112. , 112. ,  10.3,  37. , 163. ,  80. ])

### Problem 8.4

In [46]:
seafloor_crust[1,:] #everything in second row is depth

array([5460., 5634., 5734., 5749., 5750., 3905., 4558., 5876., 5937.])

### Problem 8.5

In [47]:
seafloor_crust[:,2] #index column 2

array([ 115., 5734.])

# Feedback

1. It took me about 23 hours.
2. I thought it was medium.
3. Not really